
const REDUX_CONSTANTS = {
    MOVIE_LIST: "MOVIES_LIST",
    MOVIE_DETAILS: "MOVIE_DETAILS",
    SERVICE_GET_MOVIE_LIST_LOADING: "SERVICE_GET_MOVIE_LIST_LOADING",
    SERVICE_GET_MOVIE_LIST_SUCCESS: "SERVICE_GET_MOVIE_LIST_SUCCESS",
    SERVICE_GET_MOVIE_LIST_FAILURE: "SERVICE_GET_MOVIE_LIST_FAILURE",
    SERVICE_GET_MOVIE_DETAILS_LOADING: "SERVICE_GET_MOVIE_DETAILS_LOADING",
    SERVICE_GET_MOVIE_DETAILS_SUCCESS: "SERVICE_GET_MOVIE_DETAILS_SUCCESS",
    SERVICE_GET_MOVIE_DETAILS_FAILURE: "SERVICE_GET_MOVIE_DETAILS_FAILURE"
}

export default REDUX_CONSTANTS